services:
  - type: web
    name: cultivation-game-wuxia
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
