import { Item, Technique } from '@/types/game';

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'pill_qi_1',
    name: 'Qi Condensation Pill',
    type: 'Pill',
    tier: 1,
    description: 'A basic pill refined from Spirit Grass. Restores 100 Qi and accelerates cultivation.',
    value: 15,
    effects: { qiGain: 100, hpGain: 30 },
  },
  {
    id: 'herb_spirit_grass',
    name: 'Nine-Leaf Spirit Grass',
    type: 'Herb',
    tier: 1,
    description: 'A ubiquitous herb found near Spirit Veins. Used in elementary alchemy.',
    value: 5,
  },
  {
    id: 'herb_blood_lingzhi',
    name: 'Thousand-Year Blood Lingzhi',
    type: 'Herb',
    tier: 3,
    description: 'A rare medicinal fungus soaked in spiritual blood energy. Vital for Foundation Establishment.',
    value: 120,
  },
  {
    id: 'mat_starfall_iron',
    name: 'Starfall Iron Ore',
    type: 'CraftingMaterial',
    tier: 2,
    description: 'Extraterrestrial meteorite ore imbued with cosmic energy. Essential for forging high-tier spiritual swords.',
    value: 80,
  },
  {
    id: 'pill_foundation_breakthrough',
    name: 'Foundation Pill',
    type: 'Pill',
    tier: 2,
    description: 'Guarantees stability during Foundation Establishment breakthrough.',
    value: 200,
    effects: { qiGain: 500, hpGain: 100, statBoost: { maxHp: 50 } },
  },
  {
    id: 'weapon_wooden_sword',
    name: 'Peachwood Flying Sword',
    type: 'Weapon',
    tier: 1,
    description: 'A simple enchanted sword carved from peach tree wood.',
    value: 50,
    equippableSlot: 'Weapon',
    effects: { statBoost: { attack: 15 } },
  },
  {
    id: 'weapon_heavenly_blade',
    name: 'Demon-Sealing Azure Blade',
    type: 'Weapon',
    tier: 4,
    description: 'Forged with Starfall Iron, imbued with ancient Demon Hex runes.',
    value: 1500,
    equippableSlot: 'Weapon',
    effects: { statBoost: { attack: 120, comprehension: 10 } },
  },
  {
    id: 'armor_robes',
    name: 'Sect Apprentice Robes',
    type: 'Armor',
    tier: 1,
    description: 'Durable silk robes that provide minor physical protection.',
    value: 30,
    equippableSlot: 'Armor',
    effects: { statBoost: { defense: 10, maxHp: 30 } },
  },
  {
    id: 'artifact_dragon_pendant',
    name: 'Coiling Dragon Jade Pendant',
    type: 'Artifact',
    tier: 3,
    description: 'Contains a trace of True Dragon aura. Enhances spiritual perception and law comprehension.',
    value: 800,
    equippableSlot: 'Artifact',
    effects: { statBoost: { spiritualPerception: 2, comprehension: 15 } },
  },
  {
    id: 'manual_demon_hex',
    name: 'First Hex of Demon Sealing Manual',
    type: 'Manual',
    tier: 3,
    description: 'An ancient secret scripture written by Lord Ninth. Unlocks the Hex of Spatial Binding.',
    value: 1000,
    effects: { techniqueId: 'hex_1_spatial' },
  },
  {
    id: 'manual_thunder_law',
    name: 'Nine Heavenly Thunder Sutra',
    type: 'Manual',
    tier: 4,
    description: 'Record of the ancient Lightning Sovereign. Unlocks the Lightning Dragon Slash technique.',
    value: 1800,
    effects: { techniqueId: 'thunder_dragon_slash' },
  },
];

export const ALL_TECHNIQUES: Technique[] = [
  {
    id: 'basic_strike',
    name: 'Basic Spirit Palm',
    type: 'Martial',
    element: 'Metal',
    description: 'Gathers fundamental Qi into the palm to strike down foes.',
    qiCost: 10,
    powerMultiplier: 1.2,
    requiredRealm: 'Mortal',
    requiredComprehension: 0,
    effects: { damage: 25 },
  },
  {
    id: 'fire_dragon_art',
    name: 'Nine Fire Dragon Art',
    type: 'LawSpell',
    element: 'Fire',
    description: 'Summons blazing ethereal fire dragons to burn enemies to ashes.',
    qiCost: 40,
    powerMultiplier: 2.2,
    requiredRealm: 'Qi Condensation',
    requiredComprehension: 15,
    effects: { damage: 80 },
  },
  {
    id: 'hex_1_spatial',
    name: 'First Hex: Spatial Binding',
    type: 'DemonHex',
    element: 'Demon',
    description: 'The legendary Eighth Demon Sealer technique. Freezes the space around the enemy.',
    qiCost: 80,
    powerMultiplier: 3.5,
    requiredRealm: 'Foundation Establishment',
    requiredComprehension: 30,
    effects: { damage: 180, debuffEnemy: 'Bound' },
  },
  {
    id: 'thunder_dragon_slash',
    name: 'Heavenly Thunder Dragon Slash',
    type: 'LawSpell',
    element: 'Lightning',
    description: 'Channels divine lightning into a concentrated sword beam.',
    qiCost: 110,
    powerMultiplier: 4.2,
    requiredRealm: 'Foundation Establishment',
    requiredComprehension: 35,
    effects: { damage: 280 },
  },
  {
    id: 'coiling_dragon_fist',
    name: 'Coiling Dragon Divine Punch',
    type: 'DivineArt',
    element: 'Earth',
    description: 'Manifests the phantom of an Earth Sovereign Dragon to crush mountaintops.',
    qiCost: 150,
    powerMultiplier: 5.0,
    requiredRealm: 'Core Formation',
    requiredComprehension: 50,
    effects: { damage: 450 },
  },
  {
    id: 'heavenly_healing_sutra',
    name: 'Immortal Spring Healing Sutra',
    type: 'Cultivation',
    element: 'Water',
    description: 'Channels vital water essence to restore wounds and revitalize Qi.',
    qiCost: 50,
    powerMultiplier: 1.0,
    requiredRealm: 'Qi Condensation',
    requiredComprehension: 10,
    effects: { healHp: 120 },
  },
];
