import { RealmInfo, RealmStage } from '@/types/game';

export const CULTIVATION_REALMS: Record<RealmStage, RealmInfo> = {
  'Mortal': {
    stage: 'Mortal',
    level: 1,
    maxLevel: 1,
    qiRequired: 50,
    statMultiplier: 1.0,
    title: 'Mortal Being',
    tribulationChance: 0,
  },
  'Qi Condensation': {
    stage: 'Qi Condensation',
    level: 1,
    maxLevel: 9,
    qiRequired: 100,
    statMultiplier: 1.5,
    title: 'Qi Cultivator',
    tribulationChance: 0.05,
  },
  'Foundation Establishment': {
    stage: 'Foundation Establishment',
    level: 1,
    maxLevel: 9,
    qiRequired: 300,
    statMultiplier: 2.5,
    title: 'Foundation Expert',
    tribulationChance: 0.15,
  },
  'Core Formation': {
    stage: 'Core Formation',
    level: 1,
    maxLevel: 9,
    qiRequired: 800,
    statMultiplier: 4.5,
    title: 'Golden Core Master',
    tribulationChance: 0.30,
  },
  'Nascent Soul': {
    stage: 'Nascent Soul',
    level: 1,
    maxLevel: 9,
    qiRequired: 2000,
    statMultiplier: 8.0,
    title: 'Nascent Ancestor',
    tribulationChance: 0.50,
  },
  'Spirit Severing': {
    stage: 'Spirit Severing',
    level: 1,
    maxLevel: 3, // 1st Severing, 2nd Severing, 3rd Severing
    qiRequired: 5000,
    statMultiplier: 15.0,
    title: 'Spirit Severer',
    tribulationChance: 0.70,
  },
  'Dao Seeking': {
    stage: 'Dao Seeking',
    level: 1,
    maxLevel: 3,
    qiRequired: 12000,
    statMultiplier: 28.0,
    title: 'Dao Seeker',
    tribulationChance: 0.85,
  },
  'Immortal Ascension': {
    stage: 'Immortal Ascension',
    level: 1,
    maxLevel: 9,
    qiRequired: 30000,
    statMultiplier: 60.0,
    title: 'True Immortal',
    tribulationChance: 0.95,
  },
  'Sovereign Lord': {
    stage: 'Sovereign Lord',
    level: 1,
    maxLevel: 9,
    qiRequired: 100000,
    statMultiplier: 150.0,
    title: 'Heavenly Sovereign',
    tribulationChance: 1.0,
  },
};

export const NEXT_REALM_ORDER: RealmStage[] = [
  'Mortal',
  'Qi Condensation',
  'Foundation Establishment',
  'Core Formation',
  'Nascent Soul',
  'Spirit Severing',
  'Dao Seeking',
  'Immortal Ascension',
  'Sovereign Lord',
];
