import { Recipe } from '@/lib/game/cultivationEngine';

export const CRAFTING_RECIPES: Recipe[] = [
  {
    id: 'recipe_qi_pill',
    name: 'Refine Qi Condensation Pill',
    type: 'Alchemy',
    outputItem: {
      id: 'pill_qi_1',
      name: 'Qi Condensation Pill',
      type: 'Pill',
      tier: 1,
      description: 'A basic pill refined from Spirit Grass. Restores 100 Qi and accelerates cultivation.',
      value: 15,
      effects: { qiGain: 100, hpGain: 30 },
    },
    requiredHerbName: 'Nine-Leaf Spirit Grass',
    requiredQuantity: 2,
    requiredSkill: 0,
    baseSuccessRate: 0.8,
  },
  {
    id: 'recipe_foundation_pill',
    name: 'Refine Foundation Pill',
    type: 'Alchemy',
    outputItem: {
      id: 'pill_foundation_breakthrough',
      name: 'Foundation Pill',
      type: 'Pill',
      tier: 2,
      description: 'Guarantees stability during Foundation Establishment breakthrough.',
      value: 200,
      effects: { qiGain: 500, hpGain: 100, statBoost: { maxHp: 50 } },
    },
    requiredHerbName: 'Thousand-Year Blood Lingzhi',
    requiredQuantity: 2,
    requiredSkill: 10,
    baseSuccessRate: 0.65,
  },
  {
    id: 'recipe_spirit_blade',
    name: 'Forge Spirit Steel Sword',
    type: 'Forging',
    outputItem: {
      id: 'weapon_spirit_steel_sword',
      name: 'Spirit Steel Sword',
      type: 'Weapon',
      tier: 2,
      description: 'Forged from refined iron ore soaked in spiritual vein aura.',
      value: 250,
      equippableSlot: 'Weapon',
      effects: { statBoost: { attack: 45 } },
    },
    requiredMaterialName: 'Starfall Iron Ore',
    requiredQuantity: 2,
    requiredSkill: 0,
    baseSuccessRate: 0.75,
  },
  {
    id: 'recipe_azure_armor',
    name: 'Forge Azure Dragon Vest',
    type: 'Forging',
    outputItem: {
      id: 'armor_azure_vest',
      name: 'Azure Dragon Scale Armor',
      type: 'Armor',
      tier: 3,
      description: 'Plated with dragon scale alloys, offering impenetrable defense.',
      value: 800,
      equippableSlot: 'Armor',
      effects: { statBoost: { defense: 60, maxHp: 150 } },
    },
    requiredMaterialName: 'Starfall Iron Ore',
    requiredQuantity: 4,
    requiredSkill: 15,
    baseSuccessRate: 0.6,
  },
];
